# Generated by Django 3.0.7 on 2020-08-19 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_auto_20200816_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='material_density',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='material_difficulty_factor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='surfacefinish',
            name='coating_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='surfacefinish',
            name='coating_difficulty_factor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='surfacefinish',
            name='material_coating_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='technology',
            name='postprocessing_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='technology',
            name='starup_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='technology',
            name='working_cost',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
