# Generated by Django 3.0.7 on 2020-08-19 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200819_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technology_material', to='order.Material'),
        ),
    ]
