# Generated by Django 3.0.7 on 2020-08-19 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200819_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='material',
        ),
        migrations.AddField(
            model_name='material',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_technology', to='order.Technology'),
        ),
    ]
