# Generated by Django 3.0.7 on 2020-08-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200819_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='technology',
        ),
        migrations.AddField(
            model_name='technology',
            name='material',
            field=models.ManyToManyField(blank=True, related_name='technology_material', to='order.Material'),
        ),
    ]
