# Generated by Django 3.0.7 on 2020-08-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200819_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='surface',
            field=models.ManyToManyField(blank=True, related_name='material_surface', to='order.SurfaceFinish'),
        ),
    ]
