# Generated by Django 3.0.7 on 2020-08-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_material_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='material_color', to='order.Color'),
        ),
    ]
