# Generated by Django 3.0.7 on 2020-08-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20200819_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='color',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='element_color', to='order.Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='material',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='element_material', to='order.Material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='surface',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='element_surface', to='order.SurfaceFinish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='technology',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='element_technology', to='order.Technology'),
            preserve_default=False,
        ),
    ]
