# Generated by Django 3.0.7 on 2020-08-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200819_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Element', 'verbose_name_plural': 'Elements'},
        ),
    ]
