# Generated by Django 3.0.7 on 2020-08-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200830_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source_volume',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='target_surface_area',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='target_volume',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.FloatField(default=0),
        ),
    ]
