# Generated by Django 3.0.7 on 2020-08-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20200830_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='postprocessing_time',
            field=models.FloatField(default=0.5),
        ),
    ]
