# Generated by Django 3.0.7 on 2020-08-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_technology_postprocessing_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='target_volume',
            new_name='part_volume',
        ),
    ]
