# Generated by Django 3.0.7 on 2020-08-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_surfacefinish_surface_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfacefinish',
            name='coating_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='technology',
            name='time_factor',
            field=models.FloatField(default=0),
        ),
    ]
