# Generated by Django 3.0.7 on 2020-09-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20200830_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
